[dependencies]
dioxus = { version = "0.4", features = ["desktop"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
warp = "0.3"
uuid = { version = "1", features = ["v4"] }
webrtc = "0.8"
